export type Page =
  | "dashboard"
  | "customers"
  | "loans"
  | "interest"
  | "collections"
  | "payments"
  | "reports"
  | "users"
  | "audit"
  | "auditArchive"
  | "auditRetention"
  | "compliance"
  | "backup"
  | "security";
