/* ===========================================================
   FINORA ENTERPRISE OS™

   INSTALLATION DEVICE BINDING

   MODULE  : Activation
   LAYER   : Domain Contract
   VERSION : 1.0
   STATUS  : Production Foundation

   RESPONSIBILITY:

   - Represent a native-generated installation binding identity
   - Represent the public half of the installation binding key
   - Represent an offline enrollment request
   - Represent the exact binding target carried by signed
     FINORA Control Packages

   SECURITY:

   - The private binding key is NEVER represented here.
   - The private binding key must never enter renderer state.
   - The private binding key must never enter signed packages.
   - Android private binding key belongs in Android Keystore.
   - Electron private binding key belongs in native main-process
     protected storage.
   - USB volume identity is NOT an installation identity.
   - Business Date has zero authority here.
=========================================================== */

import type {
  FinoraInstallationId,
} from "./finoraInstallation.types";

// ============================================================
// IDENTIFIERS
// ============================================================

export type FinoraInstallationBindingKeyId =
  string;

export type FinoraInstallationEnrollmentRequestId =
  string;

// ============================================================
// PLATFORM
// ============================================================

export type FinoraInstallationPlatform =
  | "WINDOWS"
  | "ANDROID";

// ============================================================
// CRYPTOGRAPHIC CONTRACT
// ============================================================

export type FinoraInstallationBindingAlgorithm =
  "ECDSA_P256_SHA256";

export type FinoraInstallationBindingPublicKeyFormat =
  "SPKI_DER_BASE64";

export type FinoraInstallationBindingSignatureEncoding =
  "IEEE_P1363";

export type FinoraInstallationBindingCanonicalization =
  "FINORA_CANONICAL_JSON_V1";

export type FinoraInstallationBindingFingerprintAlgorithm =
  "SHA-256";

// ============================================================
// PUBLIC DEVICE BINDING
// ============================================================

/**
 * Public/non-secret representation of the key generated by the
 * native Branch Client installation.
 *
 * The corresponding private key MUST remain native and
 * non-exported from the Branch Client authority boundary.
 */
export interface FinoraInstallationDeviceBinding {

  installationId:
    FinoraInstallationId;

  bindingKeyId:
    FinoraInstallationBindingKeyId;

  platform:
    FinoraInstallationPlatform;

  algorithm:
    FinoraInstallationBindingAlgorithm;

  publicKeyFormat:
    FinoraInstallationBindingPublicKeyFormat;

  /**
   * DER SubjectPublicKeyInfo encoded as standard Base64.
   *
   * Public information only.
   */
  publicKey:
    string;

  fingerprintAlgorithm:
    FinoraInstallationBindingFingerprintAlgorithm;

  /**
   * SHA-256 of the SPKI DER bytes, encoded as lowercase hex.
   */
  publicKeyFingerprint:
    string;

  createdAt:
    string;

  schemaVersion:
    1;
}

// ============================================================
// SIGNED CONTROL-PACKAGE TARGET
// ============================================================

/**
 * Exact immutable installation-binding reference that Control
 * Center packages must target.
 *
 * Public key bytes are intentionally omitted from each signed
 * entitlement package. The stable key ID + SHA-256 fingerprint
 * identify the already-enrolled native installation key.
 */
export interface FinoraInstallationBindingTarget {

  installationId:
    FinoraInstallationId;

  bindingKeyId:
    FinoraInstallationBindingKeyId;

  fingerprintAlgorithm:
    FinoraInstallationBindingFingerprintAlgorithm;

  publicKeyFingerprint:
    string;

  schemaVersion:
    1;
}

// ============================================================
// ENROLLMENT REQUEST PAYLOAD
// ============================================================

/**
 * Exportable public enrollment payload generated by the native
 * Branch Client before paid/demo provisioning.
 *
 * Later offline transport may wrap this in a .finora package.
 */
export interface FinoraInstallationEnrollmentPayload {

  requestId:
    FinoraInstallationEnrollmentRequestId;

  deviceBinding:
    FinoraInstallationDeviceBinding;

  requestedAt:
    string;

  schemaVersion:
    1;
}

// ============================================================
// ENROLLMENT SELF-PROOF
// ============================================================

export interface FinoraInstallationEnrollmentSignature {

  algorithm:
    FinoraInstallationBindingAlgorithm;

  encoding:
    FinoraInstallationBindingSignatureEncoding;

  canonicalization:
    FinoraInstallationBindingCanonicalization;

  bindingKeyId:
    FinoraInstallationBindingKeyId;

  /**
   * Standard Base64-encoded 64-byte IEEE-P1363 r||s signature.
   */
  value:
    string;
}

/**
 * Native installation signs its own canonical enrollment payload
 * with the private binding key.
 *
 * This proves possession of the private key corresponding to the
 * public key offered for enrollment.
 *
 * It does NOT itself authorize a branch. Authorization remains
 * exclusively with FINORA Control Center.
 */
export interface FinoraInstallationEnrollmentRequest {

  payload:
    FinoraInstallationEnrollmentPayload;

  signature:
    FinoraInstallationEnrollmentSignature;

  schemaVersion:
    1;
}

// ============================================================
// END
// ============================================================