/* ===========================================================
   FINORA ENTERPRISE OS™

   CUSTOMER IDENTITY FORM™
   PRESENTATION STYLES

   Responsibility:
   - Step 1 identity form presentation
   - Two-column field grid
   - FINORA dark / gold controls
   - Responsive field layout
   - No business logic
   - No form state
=========================================================== */

import type {
  CSSProperties,
} from "react";

/* ===========================================================
   ROOT
=========================================================== */

export const wrapperStyle: CSSProperties = {
  width: "100%",
  minWidth: 0,
  minHeight: 0,

  display: "flex",
  flexDirection: "column",

  gap: "10px",

  boxSizing: "border-box",
};

/* ===========================================================
   FIELD GRID
=========================================================== */

export const fieldGridStyle: CSSProperties = {
  width: "100%",

  display: "grid",

  gridTemplateColumns:
    "minmax(0, 1fr) minmax(0, 1fr)",

  columnGap: "12px",
  rowGap: "8px",

  boxSizing: "border-box",
};

/* ===========================================================
   FIELD
=========================================================== */

export const fieldStyle: CSSProperties = {
  minWidth: 0,

  display: "flex",
  flexDirection: "column",

  gap: "5px",
};

/* ===========================================================
   LABEL
=========================================================== */

export const labelStyle: CSSProperties = {
  display: "flex",
  alignItems: "center",

  minHeight: "15px",

  color: "#F3E4C2",

  fontSize: "9px",
  fontWeight: 800,

  letterSpacing: ".65px",

  textTransform: "uppercase",
};

/* ===========================================================
   REQUIRED MARK
=========================================================== */

export const requiredStyle: CSSProperties = {
  marginLeft: "4px",

  color: "#E8C778",

  fontSize: "10px",
};

/* ===========================================================
   INPUT
=========================================================== */

export const inputStyle: CSSProperties = {
  width: "100%",
  height: "38px",

  padding:
    "0 12px",

  boxSizing: "border-box",

  borderRadius: "10px",

  border:
    "1px solid rgba(214,176,106,.42)",

  outline: "none",

  background:
    "linear-gradient(180deg,rgba(255,255,255,.075),rgba(255,255,255,.035))",

  color: "#FFFFFF",

  fontSize: "11px",
  fontWeight: 500,

  boxShadow:
    "inset 0 1px 0 rgba(255,255,255,.035)",

  transition:
    "border-color .2s ease, box-shadow .2s ease, background .2s ease",

  appearance: "none",
};

/* ===========================================================
   READONLY INPUT
=========================================================== */

export const readOnlyInputStyle: CSSProperties = {
  ...inputStyle,

  background:
    "linear-gradient(180deg,rgba(214,176,106,.12),rgba(255,255,255,.035))",

  color: "#E8C778",

  fontWeight: 700,

  cursor: "default",
};

/* ===========================================================
   INPUT PLACEHOLDER
=========================================================== */

/*
  Used through the CSS class generated by IdentityForm.
  Kept here as a reusable visual token for future controls.
*/

export const placeholderColor =
  "rgba(255,255,255,.42)";

/* ===========================================================
   FULL WIDTH FIELD
=========================================================== */

export const fullWidthFieldStyle: CSSProperties = {
  gridColumn: "1 / -1",
};

/* ===========================================================
   WHATSAPP ROW
=========================================================== */

export const checkboxRowStyle: CSSProperties = {
  gridColumn: "1 / -1",

  minHeight: "30px",

  display: "flex",

  alignItems: "center",

  gap: "8px",

  padding:
    "2px 4px",

  boxSizing: "border-box",

  color:
    "rgba(255,255,255,.78)",

  fontSize: "10px",
  fontWeight: 600,
};

/* ===========================================================
   CHECKBOX
=========================================================== */

export const checkboxStyle: CSSProperties = {
  width: "15px",
  height: "15px",

  margin: 0,

  accentColor: "#D6B06A",

  cursor: "pointer",

  flexShrink: 0,
};

/* ===========================================================
   FIELD ICON
=========================================================== */

export const fieldIconStyle: CSSProperties = {
  width: "16px",
  height: "16px",

  flexShrink: 0,

  display: "inline-flex",

  alignItems: "center",
  justifyContent: "center",

  color: "#D6B06A",
};

/* ===========================================================
   INPUT WRAPPER
=========================================================== */

export const inputWrapperStyle: CSSProperties = {
  position: "relative",

  width: "100%",

  minWidth: 0,
};

/* ===========================================================
   INPUT WITH ICON
=========================================================== */

export const iconInputStyle: CSSProperties = {
  ...inputStyle,

  paddingLeft: "34px",
};

/* ===========================================================
   READONLY WITH ICON
=========================================================== */

export const iconReadOnlyInputStyle: CSSProperties = {
  ...readOnlyInputStyle,

  paddingLeft: "34px",
};

/* ===========================================================
   LOCK ICON
=========================================================== */

export const lockIconStyle: CSSProperties = {
  position: "absolute",

  left: "11px",
  top: "50%",

  transform:
    "translateY(-50%)",

  color: "#D6B06A",

  pointerEvents: "none",

  display: "flex",
  alignItems: "center",
  justifyContent: "center",
};

/* ===========================================================
   FIELD GROUP
=========================================================== */

export const fieldGroupStyle: CSSProperties = {
  minWidth: 0,

  display: "flex",
  flexDirection: "column",

  gap: "5px",
};

/* ===========================================================
   FORM FOOT NOTE
=========================================================== */

export const formNoteStyle: CSSProperties = {
  marginTop: "2px",

  color:
    "rgba(255,255,255,.42)",

  fontSize: "8px",

  lineHeight: 1.4,
};

/* ===========================================================
   MOBILE / NARROW GRID
=========================================================== */

export const mobileFieldGridStyle: CSSProperties = {
  gridTemplateColumns:
    "minmax(0, 1fr)",
};

/* ===========================================================
   SELECT / METADATA CONTROL
=========================================================== */

export const selectStyle: CSSProperties = {
  ...inputStyle,

  cursor: "pointer",

  paddingRight: "34px",
};

/* ===========================================================
   FOCUS TOKEN
=========================================================== */

export const focusShadow =
  "0 0 0 2px rgba(214,176,106,.12), 0 0 14px rgba(214,176,106,.10)";
