// ============================================================
// FINORA ENTERPRISE OS™
//
// V2 STORAGE FOUNDATION
// LOCAL STORAGE ADAPTER
//
// RESPONSIBILITY:
//
// - Local browser/Electron renderer persistence
// - Implement the common StorageAdapter contract
// - Preserve V2 localStorage-backed persistence
// - Provide safe CRUD operations
// - Enforce owner / demo storage isolation
// - Provide FINORA-only data reset
// - Keep business logic outside the storage layer
//
// IMPORTANT:
//
// - No Customer logic.
// - No Loan logic.
// - No Collection logic.
// - No Payment logic.
// - No Report logic.
// - No Electron IPC.
// - No cloud logic.
// - delete() deletes ONE record only.
// - clear() is the explicit full-entity clear operation.
// - resetFinoraData() clears ONLY FINORA-owned entities
//   inside the active REAL / DEMO storage boundary.
//
// VERSION : 2.0
// STATUS  : Production
// ============================================================


// ============================================================
// IMPORTS
// ============================================================

import {
  DataContext,
  StorageAvailability,
  StorageMode,
} from "../storage.types";

import type {
  StorageAdapter,
  StorageConfiguration,
  StorageQuery,
  StorageResult,
  StorageStatus,
  StorageWriteOptions,
} from "../storage.types";


// ============================================================
// STORAGE KEY PREFIX
// ============================================================

const STORAGE_PREFIX =
  "FINORA_V2";


// ============================================================
// ENTITY NAMES
// ============================================================

const ENTITY_CUSTOMER =
  "CUSTOMER";

const ENTITY_BUSINESS_IDENTITY =
  "BUSINESS_IDENTITY";

const ENTITY_BUSINESS_SETTINGS =
  "BUSINESS_SETTINGS";

const ENTITY_LOAN =
  "LOAN";

const ENTITY_COLLECTION =
  "COLLECTION";

const ENTITY_PAYMENT =
  "PAYMENT";

const ENTITY_NOTIFICATION =
  "NOTIFICATION";

const ENTITY_REPORT =
  "REPORT";

const ENTITY_GENERAL =
  "GENERAL";


// ============================================================
// FINORA RESET ENTITIES
//
// These are the entities owned by FINORA V2.
//
// IMPORTANT:
//
// This list is deliberately explicit.
//
// resetFinoraData() must NEVER enumerate or remove arbitrary
// localStorage keys because the browser/local storage may also
// contain unrelated application or third-party data.
//
// Only keys generated by FINORA_V2 for the active data context
// are removed.
// ============================================================

const FINORA_RESET_ENTITIES: readonly string[] = [

  ENTITY_CUSTOMER,

  ENTITY_BUSINESS_IDENTITY,

  ENTITY_BUSINESS_SETTINGS,

  ENTITY_LOAN,

  ENTITY_COLLECTION,

  ENTITY_PAYMENT,

  ENTITY_NOTIFICATION,

  ENTITY_REPORT,

  ENTITY_GENERAL,

];


// ============================================================
// LOCAL STORAGE KEY BUILDER
// ============================================================

function buildStorageKey(
  query: StorageQuery,
  options?: StorageWriteOptions,
): string {

  const ownerId =
    options?.ownerId ??
    query.ownerId;

  const demoId =
    options?.demoId ??
    query.demoId;

  const context =
    demoId
      ? `${DataContext.DEMO}_${demoId}`
      : ownerId
        ? `${DataContext.REAL}_${ownerId}`
        : DataContext.REAL;

  return [
    STORAGE_PREFIX,
    context,
    query.entity,
  ].join("_");
}


// ============================================================
// READ ARRAY
// ============================================================

function readArray<T = unknown>(
  key: string,
): T[] {

  try {

    const raw =
      localStorage.getItem(
        key,
      );

    if (!raw) {
      return [];
    }

    const parsed =
      JSON.parse(raw);

    if (!Array.isArray(parsed)) {
      return [];
    }

    return parsed as T[];

  } catch {

    return [];
  }
}


// ============================================================
// WRITE ARRAY
// ============================================================

function writeArray<T = unknown>(
  key: string,
  records: T[],
): StorageResult<T[]> {

  try {

    localStorage.setItem(
      key,
      JSON.stringify(records),
    );

    return {
      success: true,
      data: records,
    };

  } catch {

    return {
      success: false,
      error:
        "Unable to write data to local storage.",
    };
  }
}


// ============================================================
// ID EXTRACTION
// ============================================================

function getRecordId(
  record: unknown,
): string | undefined {

  if (
    typeof record !== "object" ||
    record === null
  ) {

    return undefined;
  }

  const value =
    record as Record<string, unknown>;

  if (
    typeof value.id === "string"
  ) {

    return value.id;
  }

  if (
    typeof value.customerId === "string"
  ) {

    return value.customerId;
  }

  if (
    typeof value.loanId === "string"
  ) {

    return value.loanId;
  }

  if (
    typeof value.paymentId === "string"
  ) {

    return value.paymentId;
  }

  if (
    typeof value.collectionId === "string"
  ) {

    return value.collectionId;
  }

  if (
    typeof value.notificationId === "string"
  ) {

    return value.notificationId;
  }

  return undefined;
}


// ============================================================
// LOCAL STORAGE ADAPTER
// ============================================================

export class LocalStorageAdapter
  implements StorageAdapter {

  // ==========================================================
  // MODE
  // ==========================================================

  readonly mode =
    StorageMode.LOCAL;


  // ==========================================================
  // CURRENT CONFIGURATION
  // ==========================================================

  private configuration:
    StorageConfiguration = {

    storageMode:
      StorageMode.LOCAL,

    dataContext:
      DataContext.REAL,
  };


  // ==========================================================
  // INITIALIZE
  // ==========================================================

  async initialize(
    configuration: StorageConfiguration,
  ): Promise<StorageResult<void>> {

    try {

      if (
        typeof localStorage ===
        "undefined"
      ) {

        return {
          success: false,
          error:
            "Local storage is not available.",
        };
      }

      if (
        configuration.storageMode !==
        StorageMode.LOCAL
      ) {

        return {
          success: false,
          error:
            "Local storage adapter received an invalid storage mode.",
        };
      }

      this.configuration = {
        ...configuration,
      };

      return {
        success: true,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to initialize local storage.",
      };
    }
  }


  // ==========================================================
  // AVAILABILITY
  // ==========================================================

  async isAvailable():
    Promise<boolean> {

    try {

      if (
        typeof localStorage ===
        "undefined"
      ) {

        return false;
      }

      const testKey =
        `${STORAGE_PREFIX}_AVAILABILITY_TEST`;

      localStorage.setItem(
        testKey,
        "1",
      );

      localStorage.removeItem(
        testKey,
      );

      return true;

    } catch {

      return false;
    }
  }


  // ==========================================================
  // STATUS
  // ==========================================================

  async getStatus():
    Promise<StorageStatus> {

    const available =
      await this.isAvailable();

    return {

      mode:
        StorageMode.LOCAL,

      availability:
        available
          ? StorageAvailability.READY
          : StorageAvailability.UNAVAILABLE,

      dataContext:
        this.configuration.dataContext,

      ownerId:
        this.configuration.ownerId,

      demoId:
        this.configuration.demoId,

      storageId:
        this.configuration.storageId,

      checkedAt:
        new Date().toISOString(),

      message:
        available
          ? "Local storage is ready."
          : "Local storage is unavailable.",
    };
  }


  // ==========================================================
  // GET ONE
  // ==========================================================

  async get<T = unknown>(
    query: StorageQuery,
  ): Promise<
    StorageResult<T | undefined>
  > {

    try {

      const key =
        buildStorageKey(
          query,
        );

      const records =
        readArray<T>(
          key,
        );

      if (!query.id) {

        return {
          success: true,
          data: undefined,
        };
      }

      const record =
        records.find(
          (item) =>
            getRecordId(item) ===
            query.id,
        );

      return {
        success: true,
        data: record,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to read local storage.",
      };
    }
  }


  // ==========================================================
  // GET ALL
  // ==========================================================

  async getAll<T = unknown>(
    query: StorageQuery,
  ): Promise<
    StorageResult<T[]>
  > {

    try {

      const key =
        buildStorageKey(
          query,
        );

      let records =
        readArray<T>(
          key,
        );

      if (
        typeof query.offset ===
        "number"
      ) {

        records =
          records.slice(
            query.offset,
          );
      }

      if (
        typeof query.limit ===
        "number"
      ) {

        records =
          records.slice(
            0,
            query.limit,
          );
      }

      return {
        success: true,
        data: records,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to read local storage.",
      };
    }
  }


  // ==========================================================
  // SAVE
  // ==========================================================

  async save<T = unknown>(
    record: T,
    options?: StorageWriteOptions,
  ): Promise<StorageResult<T>> {

    try {

      const id =
        getRecordId(
          record,
        );

      if (!id) {

        return {
          success: false,
          error:
            "Storage record requires a supported identifier.",
        };
      }

      const query: StorageQuery = {

        entity:
          this.resolveEntity(
            record,
          ),
      };

      const key =
        buildStorageKey(
          query,
          options,
        );

      const records =
        readArray<T>(
          key,
        );

      const existingIndex =
        records.findIndex(
          (item) =>
            getRecordId(item) ===
            id,
        );

      if (
        existingIndex !== -1
      ) {

        return {
          success: false,
          error:
            "A record with the same identifier already exists.",
        };
      }

      records.push(
        record,
      );

      const result =
        writeArray(
          key,
          records,
        );

      if (!result.success) {

        return {
          success: false,
          error:
            result.error ??
            "Unable to save record to local storage.",
        };
      }

      return {
        success: true,
        data: record,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to save record to local storage.",
      };
    }
  }


  // ==========================================================
  // UPDATE
  // ==========================================================

  async update<T = unknown>(
    record: T,
    options?: StorageWriteOptions,
  ): Promise<StorageResult<T>> {

    try {

      const id =
        getRecordId(
          record,
        );

      if (!id) {

        return {
          success: false,
          error:
            "Storage record requires a supported identifier.",
        };
      }

      const query: StorageQuery = {

        entity:
          this.resolveEntity(
            record,
          ),
      };

      const key =
        buildStorageKey(
          query,
          options,
        );

      const records =
        readArray<T>(
          key,
        );

      const index =
        records.findIndex(
          (item) =>
            getRecordId(item) ===
            id,
        );

      if (index === -1) {

        return {
          success: false,
          error:
            "Storage record was not found.",
        };
      }

      records[index] =
        record;

      const result =
        writeArray(
          key,
          records,
        );

      if (!result.success) {

        return {
          success: false,
          error:
            result.error ??
            "Unable to update record in local storage.",
        };
      }

      return {
        success: true,
        data: record,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to update record in local storage.",
      };
    }
  }


  // ==========================================================
  // DELETE ONE RECORD
  //
  // IMPORTANT:
  //
  // delete() MUST NEVER clear an entire entity when the
  // caller forgets to provide an id.
  // ==========================================================

  async delete(
    query: StorageQuery,
  ): Promise<StorageResult<void>> {

    try {

      if (!query.id) {

        return {
          success: false,
          error:
            "Storage record ID is required for delete.",
        };
      }

      const key =
        buildStorageKey(
          query,
        );

      const records =
        readArray<unknown>(
          key,
        );

      const existing =
        records.find(
          (item) =>
            getRecordId(item) ===
            query.id,
        );

      if (!existing) {

        return {
          success: false,
          error:
            "Storage record was not found.",
        };
      }

      const filtered =
        records.filter(
          (item) =>
            getRecordId(item) !==
            query.id,
        );

      const result =
        writeArray(
          key,
          filtered,
        );

      if (!result.success) {

        return {
          success: false,
          error:
            result.error ??
            "Unable to delete local storage record.",
        };
      }

      return {
        success: true,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to delete local storage record.",
      };
    }
  }


  // ==========================================================
  // REPLACE ALL
  //
  // Empty array intentionally performs no operation.
  //
  // Use clear() when the caller explicitly intends to
  // remove the complete entity collection.
  // ==========================================================

  async replaceAll<T = unknown>(
    records: T[],
    options?: StorageWriteOptions,
  ): Promise<StorageResult<void>> {

    try {

      if (!records.length) {

        return {
          success: true,
        };
      }

      const firstRecord =
        records[0];

      const query: StorageQuery = {

        entity:
          this.resolveEntity(
            firstRecord,
          ),
      };

      const key =
        buildStorageKey(
          query,
          options,
        );

      const result =
        writeArray(
          key,
          records,
        );

      if (!result.success) {

        return {
          success: false,
          error:
            result.error ??
            "Unable to replace local storage records.",
        };
      }

      return {
        success: true,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to replace local storage records.",
      };
    }
  }


  // ==========================================================
  // CLEAR
  //
  // Explicit full-entity storage clear.
  // ==========================================================

  async clear(
    query: StorageQuery,
  ): Promise<StorageResult<void>> {

    try {

      const key =
        buildStorageKey(
          query,
        );

      localStorage.removeItem(
        key,
      );

      return {
        success: true,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to clear local storage.",
      };
    }
  }


  // ==========================================================
  // RESET FINORA DATA
  //
  // IMPORTANT:
  //
  // This operation clears ONLY FINORA-owned localStorage data
  // for the currently active REAL / DEMO context.
  //
  // It does NOT:
  //
  // - clear all browser localStorage
  // - clear unrelated application keys
  // - cross owner boundaries
  // - cross Demo boundaries
  //
  // REAL:
  //
  // FINORA_V2_REAL_<ownerId>_<entity>
  //
  // DEMO:
  //
  // FINORA_V2_DEMO_<demoId>_<entity>
  //
  // Only the explicit FINORA entity list above is removed.
  // ==========================================================

  async resetFinoraData():
    Promise<
      StorageResult<void>
    > {

    try {

      if (
        typeof localStorage ===
        "undefined"
      ) {

        return {
          success: false,
          error:
            "Local storage is not available.",
        };
      }


      // --------------------------------------------------------
      // VALIDATE ACTIVE DATA CONTEXT
      // --------------------------------------------------------

      if (
        this.configuration.dataContext ===
        DataContext.REAL &&
        !this.configuration.ownerId
      ) {

        return {
          success: false,
          error:
            "A valid owner ID is required to reset REAL FINORA data.",
        };
      }


      if (
        this.configuration.dataContext ===
        DataContext.DEMO &&
        !this.configuration.demoId
      ) {

        return {
          success: false,
          error:
            "A valid Demo ID is required to reset DEMO FINORA data.",
        };
      }


      // --------------------------------------------------------
      // BUILD ACTIVE FINORA CONTEXT
      // --------------------------------------------------------

      const contextQuery: StorageQuery = {

        entity:
          ENTITY_GENERAL,

        ownerId:
          this.configuration.ownerId,

        demoId:
          this.configuration.demoId,
      };


      // --------------------------------------------------------
      // REMOVE ONLY FINORA ENTITIES
      // --------------------------------------------------------

      for (
        const entity of
        FINORA_RESET_ENTITIES
      ) {

        localStorage.removeItem(
          buildStorageKey(
            {
              ...contextQuery,

              entity,
            },
          ),
        );
      }


      return {
        success: true,
      };

    } catch {

      return {
        success: false,
        error:
          "Unable to reset FINORA data from local storage.",
      };
    }
  }


  // ==========================================================
  // ENTITY RESOLUTION
  // ==========================================================

  private resolveEntity(
    record: unknown,
  ): string {

    if (
      typeof record !== "object" ||
      record === null
    ) {

      return ENTITY_GENERAL;
    }

    const value =
      record as Record<string, unknown>;


    // --------------------------------------------------------
    // CUSTOMER
    // --------------------------------------------------------

    if (
      "identity" in value
    ) {

      return ENTITY_CUSTOMER;
    }


    // --------------------------------------------------------
    // BUSINESS IDENTITY
    // --------------------------------------------------------

    if (
      "businessId" in value &&
      "businessName" in value &&
      "branchId" in value &&
      "branchName" in value
    ) {

      return ENTITY_BUSINESS_IDENTITY;
    }


    // --------------------------------------------------------
    // BUSINESS SETTINGS
    // --------------------------------------------------------

    if (
      "businessId" in value &&
      "address" in value &&
      "currency" in value
    ) {

      return ENTITY_BUSINESS_SETTINGS;
    }


    // --------------------------------------------------------
    // LOAN
    // --------------------------------------------------------

    if (
      "outstanding" in value &&
      "loanType" in value
    ) {

      return ENTITY_LOAN;
    }


    // --------------------------------------------------------
    // COLLECTION
    // --------------------------------------------------------

    if (
      "loanId" in value &&
      "status" in value
    ) {

      return ENTITY_COLLECTION;
    }


    // --------------------------------------------------------
    // PAYMENT
    // --------------------------------------------------------

    if (
      "paymentId" in value
    ) {

      return ENTITY_PAYMENT;
    }


    // --------------------------------------------------------
    // NOTIFICATION
    // --------------------------------------------------------

    if (
      "notificationId" in value
    ) {

      return ENTITY_NOTIFICATION;
    }


    // --------------------------------------------------------
    // GENERAL
    // --------------------------------------------------------

    return ENTITY_GENERAL;
  }
}


// ============================================================
// SINGLETON
// ============================================================

export const localStorageAdapter =
  new LocalStorageAdapter();


// ============================================================
// END
// ============================================================
